### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Rithenar** [Tanttinator/BedrockTools2#1]
Using a modded pack with Bedrock Tools 2.  When starting the server I am getting an error that crashes the server. Please advise.
https://gist.github.com/Rithenar/95155ea1c2c8a2a008e7623a0e477abf

**Comment by laod** [comment]
Same crash here. Can provide my log as well if it's helpful. Mainly commenting to get added as a watcher. Thanks.

**Comment by Tanttinator** [comment]
Hey, atleast based on my own brief tests the issue should be now fixed with the newest version (1.2.4). Please notify if any undetected consequences have arisen due to the fix.

**Comment by Rithenar** [comment]
Awesome, thank you. I will install now and let you know if the issue persists.

**Comment by laod** [comment]
Thank you. My server starts with 1.2.4. I appreciate the fast fix.
